services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8888"
    ports:
      - "8888:8888"

volumes:
  static_volume:
  media_volume:
